void hello_world();
void temperature_Fahrenheit_to_Celsius();
void temperature_Fahrenheit_to_Celsius_use_float_nums();
void temperature_Fahrenheit_to_Celsius_use_for_loop();
void temperature_Fahrenheit_to_Celsius_use_symbolic_constants();
void copy_stdin_to_stdout();
void count_line_for_stdin();
void count_line_word_char_for_stdin();
void count_digit_white_space_and_others_for_stdin();
int power(int base, int n);
int print_longest_line_for_stdin();
int getline_for_me(char s[], int lim);
void copy_for_me(char to[], char from[]);
int print_longest_line_for_stdin_use_extern_vars();
int getline_for_me_use_extern_vars();
void copy_for_me_use_extern_vars();
